Traceback (most recent call last):
  File "/home/petar/PycharmProjects/diplomska_model/validate.py", line 108, in <module>
    wandb.log_model(model)
  File "/home/petar/PycharmProjects/diplomska_model/venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petar/PycharmProjects/diplomska_model/venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petar/PycharmProjects/diplomska_model/venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 3135, in log_model
    self._log_artifact(
  File "/home/petar/PycharmProjects/diplomska_model/venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 3003, in _log_artifact
    artifact, aliases = self._prepare_artifact(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petar/PycharmProjects/diplomska_model/venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 3103, in _prepare_artifact
    raise ValueError(
ValueError: You must pass an instance of wandb.Artifact or a valid file path to log_artifact